export const FEATURED_RIDES = [
  {
    name: 'Sedan',
    vehicles: 'Toyota Vios, Honda City or similar',
    description: 'Comfortable for city and highway. Great fuel economy and easy to drive.',
    price: '₱1,500',
    originalPrice: '₱2,000',
    discount: '25% OFF',
    save: '₱500',
    location: 'Cauayan',
    color: '#0f172a',
    imageKey: 'sedan',
    topPick: true,
  },
  {
    name: 'Hatchback',
    vehicles: 'Compact cars',
    description: 'Easy to park and nimble in traffic. Perfect for errands and short trips.',
    price: '₱1,200',
    originalPrice: '₱1,600',
    discount: '25% OFF',
    save: '₱400',
    location: 'Ilagan',
    color: '#0f172a',
    imageKey: 'hatchback',
  },
  {
    name: 'SUV / AUV',
    vehicles: 'Toyota Innova, Mitsubishi Xpander or similar',
    description: 'Space for the family or group trips. Reliable and versatile.',
    price: '₱2,800',
    originalPrice: '₱3,500',
    discount: '20% OFF',
    save: '₱700',
    location: 'Santiago',
    color: '#0f172a',
    imageKey: 'suv',
  },
  {
    name: 'Van / MPV',
    vehicles: 'Toyota HiAce, Nissan NV350 or similar',
    description: 'Room for the whole crew. Ideal for out-of-town trips and group getaways.',
    price: '₱3,500',
    originalPrice: '₱4,200',
    discount: '17% OFF',
    save: '₱700',
    location: 'San Mariano',
    color: '#0f172a',
    imageKey: 'family',
  },
]

export const TESTIMONIALS = [
  {
    name: 'Jun',
    role: 'Renter',
    location: 'Santiago City',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=200&h=200&fit=crop&q=80',
    quote: 'Rented an SUV for our trip to Magat Dam. Very smooth transaction! The rental partner was super helpful and the car was in great condition.',
    result: 'Trip to Magat Dam',
  },
  {
    name: 'Maria',
    role: 'Car rental partner',
    location: 'Cauayan',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&h=200&fit=crop&q=80',
    quote: 'We list our fleet on BulodPH. It helps grow our rental business. Walang sayang — our vehicles work for us and our customers.',
    result: 'Earning from our fleet',
  },
  {
    name: 'Rico',
    role: 'Renter',
    location: 'Ilagan',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=200&h=200&fit=crop&q=80',
    quote: 'Needed a car for a quick errand. Found one nearby, paid with GCash, met the rental partner in 20 minutes. So much easier than traditional rental.',
    result: 'Quick car rental',
  },
]
